travis:
  secure:
    BINSTAR_TOKEN: uF7o5OE4JWEiRATljJ1w9IX30vA4ibjkyoV24WHasoU6F5P2Iiuo/YAAsdK6UuJC8LVSxnAUPFx7MPpUUbrhd630xLMAcmnpCZJf71lrx4uurSIrrW6fsdys6NY/NFFdL0Sd/WLs+KLixC85Vqt3X+RQJUOrY6KoYqwipYmLU9G0dhCwOcbVLfC19QbJUQXVHta7l5kew6dCQ6Irm8T6GpscwQm0jTVneUy16UIQrb/zaWWlQHpC8I1y7sRJQTCBOcpssGgS2fiAQTpCJ+axvfeQ3YvcEn5LL7KuiK7oLdfxj4qWOCMwvDujMQCDZdbb0TEFtErShxmL1BGIlcgci5sIzSpe9f9kz4PG3s/BiFPa7utKhhh1LBLmc5L2izdIVIcDv07R9gknloAPfx8RRLhzWKJSCDo6nDjyCdbYQwyRDmFW/DRwMY/huI80NJoI1WmtMOrwoYeUzKvSEeP1rsJp+7O+21OEXNJuqmLeNQaBRDsgmrxK9P4P77dWNkla0vxN0mO+/WeQFYG0ElIkUl5vPBOVqZLh7y0bJVWlAelMv58DyYdM3yUEImKr1k1XCkrM8NbwJPoaRmxYigA5KRSUKe+TiGzBqZw5KtS2cUzrEJgDq74jHPn11wHKPUCpV7u51iyUNvZZ8EP1JhMmvM2oVlUFEW3nPzDjR8Biexc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
